### ISSUE TITLE
chunksize parameter in iters function not producing actual chunks

### ISSUE THREAD

**Issue by JSchoenbachler** [RevolutionAnalytics/iterators#2]
This might be a misunderstanding of what the parameter is supposed to do, but I am attempting to use the chunksize parameter when creating an iter object and it is not producing what I would expect the output to be.

Example code:

```
out = foreach(lTmp = iterators::iter(1:100, chunksize = 15L)) %do% {
  print(length(lTmp))
}
```
I would expect the output to be `15, 15, 15, 15, 15, 15, 10`, but the actual output is `1` repeated 100 times.

If I am misinterpreting, how difficult would it be to add an equivalent parameter to achieve that? I would be happy to fork the repo and put together a pull request if you could point me in the right direction.

**Comment by JSchoenbachler** [comment]
For reference, what I'm doing at the moment to achieve the desired output is essentially the following:

```
l = 1:100
chunkSize = 15L

numChunks = length(l) %/% chunkSize

out = foreach(i = 0:(numChunks)) %do% {
  startNum = (i * chunkSize) + 1
  endNum = startNum + chunkSize - 1
  if (endNum > length(l)) endNum = length(l)
  lTmp = l[startNum:endNum]
  print(lTmp)
}
```

**Comment by littlebuttermilk** [comment]
It looks like 'chunksize' for iter is only in the [matrix method](https://github.com/RevolutionAnalytics/iterators/blob/7e6c843ca1f01ef1874129bdc1a1f4ab8861849d/R/iterators.R#L39).

To get what you are looking for here, you can implement the custom [ivector iterator in the examples](https://github.com/RevolutionAnalytics/iterators/blob/master/inst/examples/ivector.R). Then
```
it <- ivector(1:100, chunkSize = 15L)
foreach(i = it) %do% { length(i) }
```
does mostly what you expect. Instead of truncating the final chunk, it shortens each of the final 5 chunks by 1. 

Your original code didn't complain, I think, because the method for 1:100 is dispatched to the default where chunkSize would be captured in ..., and misspecified arguments in ... [silently are ignored.](https://adv-r.hadley.nz/s3.html#s3-arguments)

**Comment by JSchoenbachler** [comment]
Ah, gotcha. That makes sense. Probably should have read the documentation in more detail. I'll mark it closed!
